version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14.2 # Use a Node.js image

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Meteor
          command: |
            curl https://install.meteor.com/ | sh

      - run:
          name: Run Tests
          command: |
            meteor npm test
